### ISSUE TITLE
icons to large on Mate 16.10

### ISSUE THREAD

**Issue by ghost** [B00merang-Artwork/Windows-7#2]
![bugreport](https://cloud.githubusercontent.com/assets/4351663/22933524/c4137848-f2c3-11e6-9bb0-ccb8a95bf9c7.png)

Here is a screenshot showing the problem- my first hack of the mate-panel. Can add a aero-/ vistaish css soon. don`t worry.

**Comment by Elbullazul** [comment]
I think that icon comes from the adwaita icon theme, not shure...

will check soon

**Comment by ghost** [comment]
@Elbullazul we need to define some actions images for 32x32 25x25 and
16x16. In fact i did just a small resize of 48x48 ones.
 adaptive-resize of imagemagick does the trick well enough. im not a
fan of this solution but it works at least.

**Comment by Elbullazul** [comment]
which icons did you resize?

**Comment by ghost** [comment]
actions 48 and added the missing ones to 32 25 16 . but we need to use
a not that blurring algorithm. mogrify adaptive-resize is the one i do
suggest.

**Comment by ghost** [comment]
viewmag the magnifier icons and some media player icons are especially
buggy on 16.10.

**Comment by cinnamoner** [comment]
@bluedxca93 Now wait a minute. You're telling me that's Caja? Cause it looks great with those nav buttons. I've always thought Mate is suitable for a Vista/7 lookalike. The only thing that boders me is the startmenu. No Windows looking startmenu for it. There's Brisk written in C or something but it's far from Stark. And the ancient Gnome 2 Gnomenu ... well ... nobody seems to have resurrected it. Hmmm. But that Caja screenshot looks great. I'm going to follow this. You've got me interested.

**Comment by cinnamoner** [comment]
@Elbullazul I'm not quite sure what am I seeing in the above screenie but that Caja thing looks darn good. Well yeah, bluedxca93 is right about those icons but it looks very promising. For sure. At last something worthy of my attention.

**Comment by cinnamoner** [comment]
Oh, and the yellow folders don't glow up to a blinding yellow on mouse hover, I guess. Thunar and Caja seem to be the only FMs where that annoying glow doesn't occur. That's all the more reason for me to be interested in this thread.
***
Guys, please collaborate, cause this ... It's great.

**Comment by ghost** [comment]
@cinnamoner
what could theoretically be done with brisk is to move the searchbar at bottom.

@elbullazul i do create a patch that these scaling problems don't
occur this much in mate next days.

**Comment by cinnamoner** [comment]
@bluedxca93 Interesting.

https://youtu.be/b8y1aVUgI4A

**Comment by ghost** [comment]
@cinnamoner maybe its possible to port that menu back.

**Comment by cinnamoner** [comment]
> maybe it's possible to port that menu back.

@bluedxca93 Yeah, a backport would be great. 'Cause that menu (the one in UKDE) seems a better deal than Brisk and is certainly more windowsy. Or we might take the UKDE altogether and apply a Win theme of our choice. Either way, UKDE seems an improvement over plain Mate.

**Comment by cinnamoner** [comment]
I think I'll limit myself to this thread.

**Comment by cinnamoner** [comment]
@bluedxca93 https://github.com/ukui/ukui-desktop

**Comment by cinnamoner** [comment]
@bluedxca93 And well, here's the startmenu https://github.com/ukui/ukui-menu

**Comment by ghost** [comment]
@cinnamoner its not compatible to 16.10 send bugreport on github

**Comment by ghost** [comment]
![newtheme-version](https://cloud.githubusercontent.com/assets/4351663/23094699/c4b1ae70-f5f5-11e6-9c90-570d166ddd83.png)

Now fixed. Created toolbar theme without resource from scratch.

**Comment by dominichayesferen** [comment]
@bluedxca93 I'll close this then?

**Comment by cinnamoner** [comment]
@feren Are you getting any particular pleasure out of closing threads? 😄

**Comment by cinnamoner** [comment]
@bluedxca93 I'll take the whole UI or the distro itself. It looks like a Windows 7 - W10 hybrid. I need something that works out-of-the-box. Thanks.

**Comment by ghost** [comment]
@cinnamoner the ui will be compatible to mate in future.

**Comment by ghost** [comment]
@feren where can i suggest the patched theme?. it did help a lot on mate 16.10.

**Comment by dominichayesferen** [comment]
@bluedxca93 What do you mean?

**Comment by ghost** [comment]
@feren some icons don't get resized on mate 16.10. So it is recommed
to provide them.

**Comment by Elbullazul** [comment]
you can upload the file here

**Comment by cinnamoner** [comment]
> What do you mean?

@feren Obviously, he had meant he wasn't quite finished and you closed the thread. Olala!

**Comment by cinnamoner** [comment]
@bluedxca93 Looking good.

**Comment by cinnamoner** [comment]
@bluedxca93 You've contacted the Kylin people and I've contacted the Solus people. Neither of them seem to be willing to do something about it. But I really do want the Kylin menu on Mate. What should I do?

**Comment by Elbullazul** [comment]
@cinnamoner program it from scratch

**Comment by ghost** [comment]
[patch-base64-tar-xz.txt](https://github.com/B00merang-Project/Se7en-Icon-Theme/files/787938/patch-base64-tar-xz.txt)

base64 -d patch-base* > patch.tar.xz
Anoing github but this is the only way to work around it.

**Comment by Elbullazul** [comment]
hahaha, tar.gz.txt xDDDDDDD

I'll see it asap

**Comment by ghost** [comment]
@cinnamoner
 Hi, bluedxca93, Download
the latest version of ukui-
menu will run well in ubuntu
mate.

cinnamoner
today ill test this they are planning to make it more mate compatible.
Just a fork to load other preferences as it was  done in lxde-gtk on
lubuntu.just my opinion.

**Comment by cinnamoner** [comment]
@bluedxca93 You should put tracking on me (follow option) at least for a while so you can follow my moves in conjunction with UKUI menu and Mate with ease. Sir, I'm glad about the workaround.

**Comment by cinnamoner** [comment]
@bluedxca93 Okay, I'm starting to see the picture. Looking forward to hear from you. I've got virtually no experience with Mate. Or perhaps I should say no experience at all. I recall trying it once. Hahaha!

**Comment by cinnamoner** [comment]
Potentially useful link http://www.ukui.org/

**Comment by cinnamoner** [comment]
https://github.com/ukui/ukui-menu/commit/efd9f7ecc695b62c38be5ba05c9bca2a4888e46d

**Comment by cinnamoner** [comment]
Hey, @feren Staring the UKUI? Like it, huh?

**Comment by cinnamoner** [comment]
@bluedxca93 So the Kylin people have forked Mate to provide a familiar Windows 7-like layout. Seems they have done a good job. There's a launchpad conversation with Martin.

https://github.com/ukui/ukui-menu/commit/efd9f7ecc695b62c38be5ba05c9bca2a4888e46d#commitcomment-20991430

**Comment by cinnamoner** [comment]
@bluedxca93 @Elbullazul @feren Well, I don't recall any yellow folders glowing up in Caja on mouse hover. Am I right? Just wanna be absolutely sure before engaging into Mate.

@Elbullazul Sorry man for that exchange of replies. You know what I'm talking about.

**Comment by Elbullazul** [comment]
@cinnamoner No problem old pal :)
