### ISSUE TITLE
Icon theme not recognized in Linux Mint 20

### ISSUE THREAD

**Issue by maudgalyayana** [B00merang-Artwork/Windows-7#7]
I followed this instruction:
https://www.omgubuntu.co.uk/2020/01/make-linux-mint-look-like-windows-7

I tried to change the icon theme of Linux Mint 20 Cinnamon to Windows 7 by creating a ".themes" folder in my home directory and copying the extracted zip file "Window-7-master" into it. However, the folder "Window-7-master" didn't appear in the icon box using the "themes" application, so I wasn't able to set the icons to the Windows 7 style.

**Comment by Elbullazul** [comment]
The folder must be named
`.themes` with an **s** at the end

**Comment by Elbullazul** [comment]
Also, for icon themes, you have to make a separate folder named `.icons`

**Comment by maudgalyayana** [comment]
Sorry, it was a typo. I created a folder `.themes` and `.icons` already.

**Comment by Elbullazul** [comment]
what version of mint are you running, and what desktop?

And does the GTK theme show up in the options?

**Comment by maudgalyayana** [comment]
I am using Linux Mint 20 with Cinnamon Desktop. The problem also occurs with Mint 19 Cinnamon.

The theme does not show up under the category "symbols" (see image below).

![Linux Mint  Running  - Oracle VM VirtualBox_031](https://user-images.githubusercontent.com/50839905/99907657-537d1400-2cde-11eb-8f8d-945f925a2096.png)

**Comment by Elbullazul** [comment]
it shows up on mine:
![image](https://user-images.githubusercontent.com/15310985/99917136-6262c700-2cdc-11eb-84fe-8b0c91437430.png)

try running this in a terminal:
```shell
sudo apt install git -y

cd ~/.icons
git clone https://github.com/B00merang-Artwork/Windows-7
```

see if it appears in the list

**Comment by maudgalyayana** [comment]
Now it works in both Linux Mint 19 and 20 thanks to your solution. I can choose the icon theme from the list. Thank you very much!
